name: Deploy package to NuGet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Production
    env:
      APIKEY: ${{secrets.API_KEY_NUGET}}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build ./Demiray.Core.Pagination/Demiray.Core.Pagination.csproj --configuration Release   
    - name: Pack
      run: dotnet pack ./Demiray.Core.Pagination/Demiray.Core.Pagination.csproj --configuration Release
    - name: Push
      run: dotnet nuget push ./Demiray.Core.Pagination/bin/Release/Demiray.Core.Pagination.1.0.4.1.nupkg --api-key $APIKEY --source https://api.nuget.org/v3/index.json

